version: '3'

services:
    app:
        build: .
        container_name: app_larafood
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
          - app-network
    
    webserver:
        image: nginx:alpine
        container_name: webserver_larafood
        restart: unless-stopped
        tty: true
        ports:
            - 8081:80
            - 444:443
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks: 
            - app-network
        
    db:
        image: mysql:5.7.22
        container_name: db_larafood
        restart: unless-stopped
        tty: true
        ports:
            - 33068:3306
        environment:
            MYSQL_DATABASE: larafood
            MYSQL_USER: larafood
            MYSQL_PASSWORD: larafood
            MYSQL_ROOT_PASSWORD: rootsql
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes: 
            - dbdata:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes: 
    dbdata:
        driver: local